### ISSUE TITLE
How to use the plugins?

### ISSUE THREAD

**Issue by greg121** [elParaguayo/RPI-Info-Screen#7]
Hi elParaguayo,

I wanted to run the clock plugin but got this error: "ImportError: No module name displayscreen" at line 3 in screen.py.

greg121

**Comment by elParaguayo** [comment]
Delete the plugin folders for the plugins you don't want to use. Move to the folder containing default.py and run that file `python default.py`

**Comment by greg121** [comment]
pi@raspberrypi ~/RPI-Info-Screen $ sudo python default.py
Traceback (most recent call last):
  File "default.py", line 109, in getScreens
    loadedscreen = plugin.myScreen(size, userevents=piscreenevents)
  File "/home/pi/RPI-Info-Screen/displayscreen.py", line 349, in **init**
    self.readConfig()
  File "/home/pi/RPI-Info-Screen/displayscreen.py", line 64, in readConfig
    self.setPluginVariables()
  File "./plugins/clock/screen.py", line 13, in setPluginVariables
    self.myfont = pygame.font.Font(self.clockfont, 240)
NameError: global name 'pygame' is not defined

Traceback (most recent call last):
  File "default.py", line 301, in <module>
    displayLoadingScreen(screenindex)
  File "default.py", line 174, in displayLoadingScreen
    % pluginScreens[a].screenName(),
IndexError: list index out of range

**Comment by elParaguayo** [comment]
Well that's weird! I assume the clock is the only plugin you're running? Try adding an `import pygame` line in `screen.py` in the clock folder and see if that works.

**Comment by greg121** [comment]
Thank you! And yes clock is the only plugin in the folder.

It is working now with adding the line.
